### ISSUE TITLE
No provider for NgxSmartModalService

### ISSUE THREAD

**Issue by homiodev** [AnnotationSro/ng6-file-man#31]
Angular 13.3.5
ng6-file-man 4.0.0
(PS.) Tried to add "ngx-smart-modal": "^7.4.1"

RROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(ClientModule)[NodeClickedService -> NodeClickedService -> NgxSmartModalService -> NgxSmartModalService -> NgxSmartModalService]: 
  NullInjectorError: No provider for NgxSmartModalService!
NullInjectorError: R3InjectorError(ClientModule)[NodeClickedService -> NodeClickedService -> NgxSmartModalService -> NgxSmartModalService -> NgxSmartModalService]: 
  NullInjectorError: No provider for NgxSmartModalService!
    at NullInjector.get (core.mjs:11145:1)
    at R3Injector.get (core.mjs:11312:1)
    at R3Injector.get (core.mjs:11312:1)
    at R3Injector.get (core.mjs:11312:1)
    at injectInjectorOnly (core.mjs:4765:1)
    at Module.ɵɵinject (core.mjs:4769:1)
    at Object.NodeClickedService_Factory [as factory] (ng6-file-man.mjs:353:1)
    at R3Injector.hydrate (core.mjs:11482:1)
    at R3Injector.get (core.mjs:11301:1)
    at NgModuleRef.get (core.mjs:21872:1)
    at resolvePromise (zone.js:1262:1)
    at resolvePromise (zone.js:1216:1)
    at zone.js:1329:1
    at push.46026._ZoneDelegate.invokeTask (zone.js:443:1)
    at Object.onInvokeTask (core.mjs:25579:1)
    at push.46026._ZoneDelegate.invokeTask (zone.js:442:1)
    at push.46026.Zone.runTask (zone.js:214:1)
    at drainMicroTaskQueue (zone.js:632:1)
    at push.46026.ZoneTask.invokeTask [as invoke] (zone.js:529:1)
    at invokeTask (zone.js:1714:1)
defaultErrorLogger @ core.mjs:6485
...

**Comment by Chiff** [comment]
Could you please provide minimal repo?

**Comment by DDDarylll** [comment]
did you resolve it?
